;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        haskell-indentation-common-electric-command
        indent-for-tab-command
        kill-region
        upcase-region
        ))

(setq mc/cmds-to-run-once
      '(
        c-electric-pound
        c-electric-slash
        mouse-set-region
        ))
